name = "iPlaces Website"
license = "MIT"
licenselink = "https://github.com/iplaces-org/Landing/blob/main/LICENSE.md"
description = "iPlaces - Discover, explore, and share amazing places around the world. Find hidden gems, plan adventures, and connect with fellow explorers."

homepage = "https://github.com/iplaces-org/Landing"
demosite = "https://iplaces.org/"

tags = ["landing", "travel", "places", "discovery", "responsive", "minimal", "light", "dark", "multilingual", "dark mode", "tailwind", "community"]
features = ["secure", "fast", "search", "dark mode", "widgets"]

# If the theme has a single author
[author]
  name = "iPlaces Team"
  homepage = "https://iplaces.org/"
